'use strict';
const products = [
  {id:'baymak-duotec',brand:'Baymak',name:'Duotec Compact 24 kW',category:'kombi',image:'assets/baymak-kombi.webp',tag:'Yoğuşmalı kombi',specs:'24 kW · Premix yoğuşmalı',features:['24 kW kapasite','Premix tam yoğuşmalı yapı','Isıtma ve kullanım sıcak suyu'],description:'Isıtma ve sıcak su ihtiyacını birlikte karşılayan kompakt kombi seçeneği.'},
  {id:'daikin-sensira',brand:'Daikin',name:'Sensira 12.000 BTU',category:'klima',image:'assets/daikin-klima.webp',tag:'Inverter klima',specs:'12.000 BTU · Duvar tipi split',features:['12.000 BTU soğutma kapasitesi','Inverter kompresör','Duvar tipi split iç ünite'],description:'Yaşam alanınız için soğutma ve ısıtma modları sunan inverter klima.'},
  {id:'buderus-gb062',brand:'Buderus',name:'Logamax Plus GB062',category:'kombi',image:'assets/buderus-kombi.webp',tag:'Yoğuşmalı kombi',specs:'20 kW · Tam yoğuşmalı',features:['20 kW kapasite','Tam yoğuşmalı yapı','Isıtma ve sıcak su kullanımı'],description:'Konut tipi ısıtma sistemleri için yoğuşmalı kombi seçeneği.'},
  {id:'baymak-iotherm',brand:'Baymak',name:'İotherm Monoblok 10 kW',category:'pompa',image:'assets/baymak-pompa.webp',tag:'Isı pompası',specs:'10 kW · Hava kaynaklı',features:['10 kW nominal kapasite','Hava kaynaklı monoblok sistem','Inverter kompresör'],description:'Mekânın ısıtma ihtiyacını dış havadan elde edilen enerjiyle karşılayan ısı pompası.'},
  {id:'demirdokum-plus',brand:'Demirdöküm',name:'Plus Panel Radyatör',category:'radyator',image:'assets/demirdokum-radyator.webp',tag:'Panel radyatör',specs:'600 × 800 mm · Tip 22',features:['600 × 800 mm ölçü','Tip 22 panel radyatör','Sulu ısıtma sistemleriyle kullanım'],description:'Konut ısıtma sistemi için panel radyatör seçeneği.'},
  {id:'buderus-rt24',brand:'Buderus',name:'RT24 RF Oda Termostatı',category:'termostat',image:'assets/buderus-termostat.webp',tag:'Oda termostatı',specs:'Kablosuz · Oda kontrolü',features:['Kablosuz oda kontrolü','Ortam sıcaklığı yönetimi','Cihaz uyumluluğu birlikte değerlendirilir'],description:'Yaşam alanınızdaki sıcaklığı ihtiyacınıza göre yönetmek için kablosuz oda termostatı.'},
  {id:'vaillant-turbomag',brand:'Vaillant',name:'Turbomag 125/1',category:'sofben',image:'assets/vaillant-sofben.webp',tag:'Doğalgazlı şofben',specs:'12 lt · Hermetik şofben',features:['12 litre sınıfı','Hermetik doğalgazlı şofben','Kullanım sıcak suyu'],description:'Kullanım sıcak suyu ihtiyacına yönelik doğalgazlı hermetik şofben.'},
  {id:'baymak-elegant',brand:'Baymak',name:'Elegant Plus 12.000 BTU',category:'klima',image:'assets/baymak-klima.webp',tag:'Inverter klima',specs:'12.000 BTU · Split inverter',features:['12.000 BTU kapasite','Split inverter yapı','Isıtma ve soğutma'],description:'Isıtma ve soğutma ihtiyacını bir arada karşılayan split inverter klima seçeneği.'}
];
const categories={all:'Tüm ürünler',kombi:'Kombi',klima:'Klima',pompa:'Isı pompası',radyator:'Radyatör',termostat:'Oda termostatı',sofben:'Şofben'};
let currentCategory='all',searchQuery='',showAll=false;
const quoteList=new Set();
const $=s=>document.querySelector(s);
const $$=s=>Array.from(document.querySelectorAll(s));
const escapeHTML=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalized=value=>String(value).toLocaleLowerCase('tr-TR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i');
function matchingProducts(){return products.filter(p=>(currentCategory==='all'||p.category===currentCategory)&&(!searchQuery||normalized(p.brand+' '+p.name+' '+p.specs+' '+categories[p.category]).includes(normalized(searchQuery))));}
function renderProducts(){
  const matched=matchingProducts();const visible=currentCategory==='all'&&!searchQuery&&!showAll?matched.slice(0,4):matched;
  $('#product-grid').innerHTML=visible.length?visible.map(p=>`<article class="product-card"><button class="product-photo" data-detail="${p.id}" aria-label="${escapeHTML(p.brand+' '+p.name)} ürününü incele"><img src="${p.image}" alt="${escapeHTML(p.brand+' '+p.name)}" width="1000" height="1000" loading="lazy"><span class="product-tag">${p.tag}</span></button><div class="product-info"><span class="product-brand">${p.brand}</span><h3>${p.name}</h3><div class="product-specs">${p.specs}</div><div class="product-info-bottom"><button class="product-detail-button" data-detail="${p.id}">Ürünü incele</button><button class="add-button" data-add="${p.id}" aria-label="${escapeHTML(p.brand+' '+p.name)} teklif listesine ekle" aria-pressed="${quoteList.has(p.id)}">${quoteList.has(p.id)?'✓':'+'}</button></div></div></article>`).join(''):'<div class="empty-state"><h3>Bu aramada ürün bulunamadı.</h3><p>Başka bir ürün veya marka adı deneyin.</p><button class="button button-outline" data-reset-search>Aramayı temizle</button></div>';
  $('#result-count').textContent=searchQuery?`${matched.length} arama sonucu`:`${visible.length} ürün`;
  $('.filter[data-filter="all"]').textContent=showAll?'Tüm ürünler':'Öne çıkanlar';
  $('#show-all').hidden=currentCategory!=='all'||!!searchQuery||showAll;
  $('#clear-search').hidden=!searchQuery;
  $$('.filter').forEach(b=>{const active=b.dataset.filter===currentCategory;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});
}
function chooseCategory(category,scroll=false){if(!Object.hasOwn(categories,category))throw new Error('Geçersiz kategori');currentCategory=category;searchQuery='';$('#search-input').value='';showAll=category==='all'&&scroll;renderProducts();$('#main-nav').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false');if(scroll)$('#urunler').scrollIntoView({behavior:'smooth'});return matchingProducts();}
let toastTimer;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2800);}
function addToQuote(id){const p=products.find(p=>p.id===id);if(!p)throw new Error('Ürün bulunamadı');if(quoteList.has(id)){toast('Bu ürün zaten teklif listenizde.');return p;}quoteList.add(id);$('#quote-count').textContent=String(quoteList.size);renderProducts();renderQuoteItems();toast('Ürün teklif listenize eklendi.');return p;}
function renderQuoteItems(){$('#quote-items').innerHTML=quoteList.size?`<p class="eyebrow">İLGİLENDİĞİNİZ ÜRÜNLER (${quoteList.size})</p>`+[...quoteList].map(id=>{const p=products.find(p=>p.id===id);return `<div class="quote-item"><img src="${p.image}" alt="" width="44" height="48"><span>${p.brand} ${p.name}</span><button data-remove="${p.id}" aria-label="${escapeHTML(p.name)} listeden çıkar">Çıkar</button></div>`;}).join(''):'<p class="quote-empty">Henüz ürün eklemediniz. Ürün seçmeden de ihtiyacınızı anlatabilirsiniz.</p>';}
function closeDialogs(){$$('dialog[open]').forEach(d=>d.close());}
function openQuote(){closeDialogs();renderQuoteItems();$('#quote-form').hidden=false;$('#quote-preview').hidden=true;$('#quote-dialog').showModal();}
function openProduct(id){const p=products.find(p=>p.id===id);if(!p)return;$('#product-detail').innerHTML=`<div class="product-detail-layout"><img src="${p.image}" width="1000" height="1000" alt="${escapeHTML(p.brand+' '+p.name)}"><div><p class="eyebrow">${p.brand} · ${categories[p.category]}</p><h2 id="product-detail-title">${p.name}</h2><p>${p.description}</p><ul>${p.features.map(f=>`<li>${f}</li>`).join('')}</ul><button class="button button-primary" data-detail-add="${p.id}">Teklif listesine ekle</button><button class="button button-outline" data-open-quote>Bu ürün için bilgi al</button></div></div><p class="detail-note">Ürün görselleri örnek katalogdan alınmıştır. Fiyat ve kurulum kapsamı teklif aşamasında belirlenir.</p>`;$('#product-dialog').showModal();}
const services=[
 {eyebrow:'ÖNCE İHTİYACINIZI ANLAYALIM',title:'Her mekânın<br>ihtiyacı farklı.',description:'Metrekare, yalıtım, cephe ve kullanım alışkanlıkları. Doğru kapasiteyi seçmek için tüm detayları birlikte değerlendirelim.',points:['Mekân ve kullanım ihtiyacı','Uygun kapasite ve model seçimi','Ürünlerin birlikte değerlendirilmesi']},
 {eyebrow:'SEÇİMDEN SONRAKİ ADIM',title:'Kurulumu da<br>birlikte planlayalım.',description:'Cihazın yeri, mevcut tesisat ve montaj gereksinimleri. Satın alma kararınızdan önce kurulumun kapsamını netleştirelim.',points:['Mevcut tesisatın değerlendirilmesi','Cihaz yerleşimi ve bağlantı planı','Montaj kapsamı ve zamanlama']},
 {eyebrow:'KONFORUNUZ DEVAM ETSİN',title:'Cihazınıza uygun<br>bakım planı.',description:'Kullandığınız cihazın markası, modeli ve bakım ihtiyacını belirtin. Servis sürecini ürününüze göre değerlendirelim.',points:['Marka ve model bilgisi','Bakım veya arıza ihtiyacının tanımı','Uygun servis yönlendirmesi']}
];
function chooseService(index){const s=services[index];if(!s)return;$$('[data-service]').forEach(b=>{const active=Number(b.dataset.service)===index;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;});$('.service-panel .eyebrow').textContent=s.eyebrow;$('.service-number').textContent=String(index+1).padStart(2,'0');$('#service-title').innerHTML=s.title;$('#service-description').textContent=s.description;$('#service-points').innerHTML=s.points.map(p=>`<li>${p}</li>`).join('');$('#service-panel').setAttribute('aria-labelledby','service-tab-'+index);}
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;
  if(b.dataset.filter!==undefined){e.preventDefault();chooseCategory(b.dataset.filter,b.tagName==='A');}
  if(b.hasAttribute('data-open-quote')||b.hasAttribute('data-open-list')){if(b.closest('#product-dialog')){const id=$('[data-detail-add]')?.dataset.detailAdd;if(id)addToQuote(id);}openQuote();}
  if(b.dataset.detail)openProduct(b.dataset.detail);
  if(b.dataset.add)addToQuote(b.dataset.add);
  if(b.dataset.detailAdd){addToQuote(b.dataset.detailAdd);openQuote();}
  if(b.dataset.remove){quoteList.delete(b.dataset.remove);$('#quote-count').textContent=String(quoteList.size);renderQuoteItems();renderProducts();}
  if(b.hasAttribute('data-close'))b.closest('dialog').close();
  if(b.hasAttribute('data-reset-search'))resetSearch();
  if(b.dataset.service!==undefined)chooseService(Number(b.dataset.service));
  if(b.dataset.serviceLink!==undefined)chooseService(Number(b.dataset.serviceLink));
  if(b.dataset.season!==undefined){$$('[data-season]').forEach(s=>{const active=s===b;s.classList.toggle('active',active);s.setAttribute('aria-pressed',String(active));});chooseCategory(b.dataset.season);$('#products-title').textContent=b.dataset.season==='klima'?'Yazın havasını değiştirin.':b.dataset.season==='kombi'?'Kışa sıcak bir başlangıç.':'Evinize yakışan çözümler.';}
});
$('#menu-toggle').addEventListener('click',()=>{const isOpen=$('#main-nav').classList.toggle('open');$('#menu-toggle').setAttribute('aria-expanded',String(isOpen));$('#menu-toggle').setAttribute('aria-label',isOpen?'Menüyü kapat':'Menüyü aç');});
$('#main-nav').addEventListener('click',e=>{if(e.target.closest('a')){$('#main-nav').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false');}});
$('#show-all').addEventListener('click',()=>{showAll=true;renderProducts();});
$('#search-form').addEventListener('submit',e=>{e.preventDefault();currentCategory='all';searchQuery=$('#search-input').value.trim();showAll=true;renderProducts();$('#urunler').scrollIntoView({behavior:'smooth'});});
function resetSearch(){searchQuery='';$('#search-input').value='';currentCategory='all';showAll=false;renderProducts();}
$('#clear-search').addEventListener('click',resetSearch);
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
$('.service-tabs').addEventListener('keydown',e=>{const tabs=$$('[data-service]');let index=tabs.indexOf(document.activeElement);if(index<0)return;const keys=['ArrowDown','ArrowUp','ArrowLeft','ArrowRight','Home','End'];if(!keys.includes(e.key))return;e.preventDefault();if(e.key==='Home')index=0;else if(e.key==='End')index=tabs.length-1;else index=(index+(['ArrowRight','ArrowDown'].includes(e.key)?1:-1)+tabs.length)%tabs.length;chooseService(index);tabs[index].focus();});
$('#quote-form').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.target);const lines=['Kombi Klima Go — Teklif önizlemesi','',`Ad: ${data.get('name')}`,`Telefon: ${data.get('phone')}`,`İhtiyaç: ${data.get('need')}`,`Konum: ${data.get('location')||'Belirtilmedi'}`,'','İlgilenilen ürünler:',...([...quoteList].length?[...quoteList].map(id=>{const p=products.find(p=>p.id===id);return `• ${p.brand} ${p.name}`;}):['Ürün danışmanlığı isteniyor.']),'',`Not: ${data.get('note')||'—'}`];$('#preview-text').textContent=lines.join('\n');$('#quote-form').hidden=true;$('#quote-preview').hidden=false;$('#quote-preview').scrollIntoView({block:'nearest'});});
$('#edit-preview').addEventListener('click',()=>{$('#quote-form').hidden=false;$('#quote-preview').hidden=true;$('#quote-form input').focus();});
$('#copy-preview').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#preview-text').textContent);toast('Teklif metni kopyalandı.');}catch{const selection=window.getSelection();const range=document.createRange();range.selectNodeContents($('#preview-text'));selection.removeAllRanges();selection.addRange(range);toast('Metin seçildi. Kopyalamak için Ctrl+C kullanın.');}});
renderProducts();renderQuoteItems();
if(document.modelContext?.registerTool){
  const lifetime=new AbortController();
  const tools=[{name:'search_product_catalogue',title:'Ürün kataloğunda ara',description:'Örnek katalogda ürün arar ve görünür vitrini günceller. Sipariş oluşturmaz.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:100},category:{type:'string',enum:Object.keys(categories)}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||(input.query!==undefined&&(typeof input.query!=='string'||input.query.length>100))||(input.category!==undefined&&!Object.hasOwn(categories,input.category)))throw new Error('Geçersiz arama');currentCategory=input.category||'all';searchQuery=input.query||'';showAll=true;$('#search-input').value=searchQuery;renderProducts();return matchingProducts().map(({id,brand,name,category})=>({id,brand,name,category}));}},{name:'stage_quote_products',title:'Teklif listesine ürün ekle',description:'Seçili ürünleri örnek teklif listesine ekler. Herhangi bir talep göndermez veya sipariş vermez.',inputSchema:{type:'object',properties:{productIds:{type:'array',items:{type:'string'},minItems:1,maxItems:8}},required:['productIds'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!Array.isArray(input.productIds)||input.productIds.length<1||input.productIds.length>8||input.productIds.some(id=>typeof id!=='string'||!products.some(p=>p.id===id)))throw new Error('Geçersiz ürün listesi');input.productIds.forEach(addToQuote);return{productIds:[...quoteList],sent:false};}}];
  for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifetime.signal})).catch(()=>{});}catch{}}
  window.addEventListener('pagehide',()=>lifetime.abort(),{once:true});
}
